name: btc_address_validate
version: 1.0.0
description: A minimal library to validate Bitcoin mainnet and testnet addresses

dependencies:
    bech32: ^0.2.0
    base58check: ^2.0.0
    equatable: ^2.0.0

environment:
    sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
    pedantic: ^1.11.0